import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/user_model.dart';

class FirestoreServices {
  //attributes
  static final _db = FirebaseFirestore.instance;
  static final _usersCollection =
      FirebaseFirestore.instance.collection('users');

//creates a user , or if the user already exists, update their information
//parameters : user : a user that you create after succesfully collecting the data you need in the update profile screen
  static Future createOrUpdateUser(User user) async {
    //this generates a new empty doc in users collection and gives it the user id to set as the document id
    final newUserDoc = _usersCollection.doc(user.uID); //this is a doc reference
    await newUserDoc.set(user.toFirestore());
  }

  //if this function finds the user your are looking for it returns it, else it will return null
  /*parameters :
  uID : this is the unique id generated by firebase auth once the user signs up for the first time
  you can fetch it anywhere in the project with 
  FirebaseAuth.instance.currentUser!.uid
  */
  static Future<User?> fetchUser(String? uID) async {
    final userDoc =
        await _usersCollection.doc(uID).get(); //this is a doc snapshot
    if (userDoc.exists) {
      return User.fromFirestore(userDoc);
    } else {
      return null;
    }
  }

  //this function fetches multiples users from the database
  //by default all returend users are sorted based on their total rating
  //you choose how many users you want to fetch with the parameter 'number'
  //you can optionally also pass a second parameter 'lastUser'
  /*normally if you want an infinitely scrolling list (like a user leaderboard) where the application keeps
    fetching more users to display as we scroll down the list , you don't want the db to fetch every single user stored at once
    because this would be terrible for performace*/
  //instead if you pass the lastUser parameter, the db will start fetching users after that user
  //I.E lets say you fetched users 1 2 3 from the db
  //now you want to fetch more users but don't want to fetch 1 2 3 again
  //pass User number 3 as a paramter to this function and it will start fetching from user 4
  static Future<List<User?>> fetchAllUsersByrating(int number,
      {User? lastUser}) async {
    final userDocs;
    List<User?> userslist = [];
    if (lastUser != null) {
      final lastUserDoc = await _usersCollection.doc(lastUser.uID).get();
      if (lastUserDoc.exists) {
        userDocs = await _usersCollection
            .orderBy('totalRating')
            .startAfterDocument(lastUserDoc)
            .limit(number)
            .get();
      } else {
        userDocs =
            await _usersCollection.orderBy('totalRating').limit(number).get();
      }
    } else {
      userDocs =
          await _usersCollection.orderBy('totalRating').limit(number).get();
    }
    for (final doc in userDocs.docs) {
      userslist.add(User.fromFirestore(doc));
    }
    return userslist;
  }
}

class StorageServices {}
